Repository AgricHub/AgricHub-Emarket, pull requests merged in 2023-10, with the labels that each got.

#29 Create greetings.yml
  .github/workflows/greetings.yml
Labels: HACTOBERFEST-ACCEPTED

#31 About hub
  website/app/about/page.tsx
  website/app/blog/page.tsx
Labels: Ready for review

#33 About hub
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: Ready for review, HACTOBERFEST-ACCEPTED

#35 Move to production
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  website/app/about/page.tsx
  website/app/blog/page.tsx
  website/components/About/AboutSectionOne.tsx
  website/components/About/AboutSectionTwo.tsx
  website/components/Footer/index.tsx
Labels: Ready for review, HACTOBERFEST-ACCEPTED

#40 Move to production
  website/components/About/AboutSectionTwo.tsx
  website/components/Hero/index.tsx
  website/package-lock.json
  website/pnpm-lock.yaml
Labels: Ready for review

#43 Update blogData.tsx
  website/components/Blog/blogData.tsx
Labels: HACTOBERFEST-ACCEPTED

#44 Update index.tsx
  website/components/Testimonials/index.tsx
Labels: enhancement, HACTOBERFEST-ACCEPTED

#52 Update NewsLatterBox.tsx
  website/components/Contact/NewsLatterBox.tsx
Labels: Ready for review, HACTOBERFEST-ACCEPTED

#53 Update LICENSE.md
  LICENSE.md
Labels: documentation, Ready for review, HACTOBERFEST-ACCEPTED
